Repository av1m/Apartments, pull requests merged in 2020-06, with the labels that each got.

#38 Fix the name of the json file containing the 500 apartments
  src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvert.java
Labels: bug

#36 Fix #20 : Creating a json adapter
  src/main/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvert.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvertTest.java
Labels: enhancement

#54 Use of convention for unit tests
  pom.xml
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/ApartmentFactoryTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/ApartmentTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/json/JsonConvertTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/xml/ReadApartmentsXMLFormatTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/apartment/xml/XMLPropertiesTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/distance/DistanceSubwayTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/BooleanValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/DiscreteValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/LinearAVFTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/LinearValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/PieceWiseLinearValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ReversedLinearValueFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ValueDistFunctionTests.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/ProfileTests.java
Labels: documentation, enhancement

#48 Fix #47 : Add cache for github actions
  .github/workflows/maven.yml
Labels: enhancement

#52 Add profile manager
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/Profile.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/ProfileManager.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/ProfileType.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/ProfileManagerTest.java
Labels: Priority

#60 Fix builder de profile
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/Profile.java
Labels: bug

#58 Changed the Profile range attributes to a EnumMap<Criterion, Range>
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/Profile.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/ProfileManagerTest.java
Labels: enhancement

#56 Reorganization according to Criterion
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunction.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/Criterion.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/LinearAVF.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ValueFunctionType.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/ApartmentValueFunctionTests.java
Labels: enhancement

#45 Addition of the QuestionPriceArea class
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/LinearAVF.java
  src/main/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/QuestionPriceArea.java
  src/test/java/io/github/oliviercailloux/y2018/apartments/valuefunction/profile/QuestionPriceAreaTests.java
Labels: Priority
